AssignmentPRN221_TaskManagement/Pages/Groups/AddGroup.cshtml.cs
using AssignmentPRN221_TaskManagement.DataAccess;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Security.Claims;

namespace AssignmentPRN221_TaskManagement.Pages.Groups
{
    [Authorize]
    public class AddGroupModel : PageModel
    {      
        GroupManagementContext context = new GroupManagementContext();
        public void OnGet()
        {
            var identity = HttpContext.User.Identity as ClaimsIdentity;
            IEnumerable<Claim> claims = identity.Claims;
            string username = claims.FirstOrDefault(c => c.Type == ClaimTypes.Name)?.Value;
            User curUser = context.Users.SingleOrDefault(u => u.Username == username);
            ViewData["curUser"] = curUser;
        }
        public Boolean CheckGroupName(string name)
        {
            try
            {
                var groupname = context.Groups.Where(g => g.GroupName.Equals(name));
                return groupname.ToList().Count() != 0;
            }
            catch (Exception ex)
            {
                ex.StackTrace.ToString();
                return false;
            }
        }

        public void OnPost(string groupname, string description, string purpose, string state)
        {

            var identity = HttpContext.User.Identity as ClaimsIdentity;
            IEnumerable<Claim> claims = identity.Claims;
            string username = claims.FirstOrDefault(c => c.Type == ClaimTypes.Name)?.Value;
            User curUser = context.Users.SingleOrDefault(u => u.Username == username);
            ViewData["curUser"] = curUser;


            Group group = new Group();
            int privateOrPublic;
            Boolean isExist = CheckGroupName(groupname);
            if (isExist == true)
            {
                ViewData["MessAddGroup"] = "Group name duplicate";
            }

            else
            {
                group.GroupName = groupname;
                group.Description = description;
                if (state.Equals("Private"))
                {
                    privateOrPublic = 0;
                }
                else
                {
                    privateOrPublic = 1;
                }
                group.State = privateOrPublic;
                group.Purpose = purpose;
                group.Status = true;
                context.Groups.Add(group);
                context.SaveChanges();

                //Add first member
                Member m = new Member { UserId = curUser.UserId, GroupId = group.GroupId, RoleId = 1, State = 1, Status = true };
                context.Members.Add(m);
                context.SaveChanges();


                ViewData["MessAddGroup"] = "Add group successfully";
            }
        }
    }
}

AssignmentPRN221_TaskManagement/Pages/Groups/EditGroup.cshtml.cs
using AssignmentPRN221_TaskManagement.DataAccess;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Security.Claims;
using System.Text.RegularExpressions;
using Group = AssignmentPRN221_TaskManagement.DataAccess.Group;

namespace AssignmentPRN221_TaskManagement.Pages.Groups
{
    [Authorize]
    public class EditGroupModel : PageModel
    {
        GroupManagementContext context = new GroupManagementContext();
        public void OnGet(string groupid)
        {
            var identity = HttpContext.User.Identity as ClaimsIdentity;
            IEnumerable<Claim> claims = identity.Claims;
            string username = claims.FirstOrDefault(c => c.Type == ClaimTypes.Name)?.Value;
            User curUser = context.Users.SingleOrDefault(u => u.Username == username);
            Group group = context.Groups.SingleOrDefault(g => g.GroupId == int.Parse(groupid));

            ViewData["curUser"] = curUser;
            ViewData["group"] = group;
        }

        public Boolean CheckGroupName(string name)
        {
            try
            {
                var groupname = context.Groups.Where(g => g.GroupName.Equals(name));
                return groupname.ToList().Count() != 0;
            }
            catch (Exception ex)
            {
                ex.StackTrace.ToString();
                return false;
            }
        }
        public void OnPost(string grId, string groupname, string description, string purpose, string state)
        {

            var identity = HttpContext.User.Identity as ClaimsIdentity;
            IEnumerable<Claim> claims = identity.Claims;
            string username = claims.FirstOrDefault(c => c.Type == ClaimTypes.Name)?.Value;
            User curUser = context.Users.SingleOrDefault(u => u.Username == username);
            Group group = context.Groups.SingleOrDefault(g => g.GroupId == int.Parse(grId));
            ViewData["curUser"] = curUser;
            ViewData["group"] = group;

            int privateOrPublic;
            Boolean isExist = CheckGroupName(groupname);
            if (isExist == true)
            {
                ViewData["MessAddGroup"] = "Group name duplicate";
            }

            else
            {
                group.GroupName = groupname;
                group.Description = description;
                if (state.Equals("Private"))
                {
                    privateOrPublic = 0;
                }
                else
                {
                    privateOrPublic = 1;
                }
                group.State = privateOrPublic;
                group.Purpose = purpose;
                group.Status = true;
                context.SaveChanges();


                ViewData["MessEditGroup"] = "Edit group successfully";
            }
        }
    }
}

AssignmentPRN221_TaskManagement/Pages/Groups/GroupDetail.cshtml.cs
using AssignmentPRN221_TaskManagement.DataAccess;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;

namespace AssignmentPRN221_TaskManagement.Pages.Groups
{
    [Authorize]
    public class GroupDetailModel : PageModel
    {
        GroupManagementContext context = new GroupManagementContext();
        public void OnGet(string groupid)
        {
            var identity = HttpContext.User.Identity as ClaimsIdentity;
            IEnumerable<Claim> claims = identity.Claims;
            string username = claims.FirstOrDefault(c => c.Type == ClaimTypes.Name)?.Value;
            User user = context.Users.SingleOrDefault(u => u.Username == username);
            Group group = context.Groups.SingleOrDefault(g => g.GroupId == int.Parse(groupid));

            List<Member> members = context.Members.Include(m => m.Group).Include(m => m.Role).Include(m => m.User).Where(m => m.GroupId == int.Parse(groupid) && m.Status == true && m.State == 1).ToList();
            foreach (Member member in members)
            {
                if (member.UserId == user.UserId)
                {
                    ViewData["usermember"] = member;
                }
            }

            ViewData["user"] = user;
            ViewData["group"] = group;
            ViewData["members"] = members;
        }

        public void OnPostRemoveMember(string userid, string groupid)
        {
            List<Member> _members = context.Members.Where(m => m.UserId == int.Parse(userid) && m.GroupId == int.Parse(groupid)).ToList();
            foreach (Member m in _members)
            {
                m.Status = false;
            }

            context.SaveChanges();


            var identity = HttpContext.User.Identity as ClaimsIdentity;
            IEnumerable<Claim> claims = identity.Claims;
            string username = claims.FirstOrDefault(c => c.Type == ClaimTypes.Name)?.Value;
            User user = context.Users.SingleOrDefault(u => u.Username == username);
            Group group = context.Groups.SingleOrDefault(g => g.GroupId == int.Parse(groupid));

            List<Member> members = context.Members.Include(m => m.Group).Include(m => m.Role).Include(m => m.User).Where(m => m.GroupId == int.Parse(groupid) && m.Status == true && m.State == 1).ToList();
            foreach (Member member in members)
            {
                if (member.UserId == user.UserId)
                {
                    ViewData["usermember"] = member;
                }
            }
            ViewData["user"] = user;
            ViewData["group"] = group;
            ViewData["members"] = members;
        }
    }
}

AssignmentPRN221_TaskManagement/Pages/Groups/InviteMember.cshtml.cs
using AssignmentPRN221_TaskManagement.DataAccess;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Data;
using System.Security.Claims;
using System.Text.RegularExpressions;
using Group = AssignmentPRN221_TaskManagement.DataAccess.Group;

namespace AssignmentPRN221_TaskManagement.Pages.Groups
{
    [Authorize]
    public class InviteMemberModel : PageModel
    {
        GroupManagementContext context = new GroupManagementContext();
        public void OnGet(string groupid)
        {
            var identity = HttpContext.User.Identity as ClaimsIdentity;
            IEnumerable<Claim> claims = identity.Claims;
            string username = claims.FirstOrDefault(c => c.Type == ClaimTypes.Name)?.Value;
            User curUser = context.Users.SingleOrDefault(u => u.Username == username);
            List<Role> roles = context.Roles.ToList();
            Group group = context.Groups.SingleOrDefault(g => g.GroupId == int.Parse(groupid));

            ViewData["curUser"] = curUser;
            ViewData["group"] = group;
            ViewData["roles"] = roles;
        }
        public void OnPost(string groupid, string username, string role)
        {
            var identity = HttpContext.User.Identity as ClaimsIdentity;
            IEnumerable<Claim> claims = identity.Claims;
            string curUsername = claims.FirstOrDefault(c => c.Type == ClaimTypes.Name)?.Value;
            User curUser = context.Users.SingleOrDefault(u => u.Username == curUsername && u.Status == true);
            User userFound = context.Users.SingleOrDefault(u => u.Username == username && u.Status == true);
            Group group = context.Groups.SingleOrDefault(g => g.GroupId == int.Parse(groupid));
            List<Role> roles = context.Roles.ToList();
            Member member = context.Members.SingleOrDefault(m => m.GroupId == int.Parse(groupid) && m.User.Username.Equals(username) && m.State == 0 && m.Status == true);

            ViewData["curUser"] = curUser;
            ViewData["group"] = group;
            ViewData["roles"] = roles;

            if (userFound != null && member == null)
            {
                Member memberadd = new Member { GroupId = int.Parse(groupid), RoleId = int.Parse(role), UserId = userFound.UserId, Status = true, State = 0 };
                context.Members.Add(memberadd);
                context.SaveChanges();
                ViewData["MessInvite"] = "Invite has been sent";
            }
            else if (userFound == null)
            {
                ViewData["MessInvite"] = "User not exist";
            }
            else if (member != null)
            {
                ViewData["MessInvite"] = "Member already in group";
            }
            else
            {
                ViewData["MessInvite"] = "Login failed";
            }

        }
    }
}

AssignmentPRN221_TaskManagement/Pages/Groups/UpdateMember.cshtml.cs
using AssignmentPRN221_TaskManagement.DataAccess;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;

namespace AssignmentPRN221_TaskManagement.Pages.Groups
{
    [Authorize]
    public class UpdateMemberModel : PageModel
    {
        GroupManagementContext context = new GroupManagementContext();
        public void OnGet(string userid, string groupid)
        {
            var identity = HttpContext.User.Identity as ClaimsIdentity;
            IEnumerable<Claim> claims = identity.Claims;
            string username = claims.FirstOrDefault(c => c.Type == ClaimTypes.Name)?.Value;
            User curUser = context.Users.SingleOrDefault(u => u.Username == username);

            User user = context.Users.SingleOrDefault(u => u.UserId == int.Parse(userid));
            List<Role> roles = context.Roles.ToList();
            List<Member> members = context.Members.Include(m => m.Group).Include(m => m.Role).Include(m => m.User).Where(m => m.GroupId == int.Parse(groupid) && m.Status == true).ToList();
            foreach (Member member in members)
            {
                if (member.UserId == user.UserId)
                {
                    ViewData["usermember"] = member;
                }
            }


            ViewData["curUser"] = curUser;
            ViewData["user"] = user;
            ViewData["roles"] = roles;
        }

        public void OnPost(string role, string userid, string groupid)
        {
            var identity = HttpContext.User.Identity as ClaimsIdentity;
            IEnumerable<Claim> claims = identity.Claims;
            string username = claims.FirstOrDefault(c => c.Type == ClaimTypes.Name)?.Value;
            User curUser = context.Users.SingleOrDefault(u => u.Username == username);
            User user = context.Users.SingleOrDefault(u => u.UserId == int.Parse(userid));

            List<Member> members = context.Members.Include(m => m.Group).Include(m => m.Role).Include(m => m.User).Where(m => m.GroupId == int.Parse(groupid) && m.Status == true).ToList();
            foreach (Member member in members)
            {
                if (member.UserId == int.Parse(userid))
                {
                    //context.Entry(member).CurrentValues.SetValues(role);
                    member.RoleId = int.Parse(role);
                    context.SaveChanges();
                    ViewData["usermember"] = member;
                }
            }
            context.SaveChanges();
            List<Role> roles = context.Roles.ToList();


            ViewData["curUser"] = curUser;
            ViewData["user"] = user;
            ViewData["roles"] = roles;
        }
    }
}

AssignmentPRN221_TaskManagement/Pages/Groups/GroupDetail.cshtml
@page
@model AssignmentPRN221_TaskManagement.Pages.Groups.GroupDetailModel
@using AssignmentPRN221_TaskManagement.DataAccess
@using System.Security.Claims
@{
    Layout = null;
    User user = (User)ViewData["user"];
    Member usermember = (Member)ViewData["usermember"];
    Group gr = (Group)ViewData["group"];

    List<Member> members = (List<Member>)ViewData["members"];

}

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>HomePage</title>

    <!-- Custom fonts for this template-->
    <script src="https://kit.fontawesome.com/aca8a481b2.js" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
          rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="~/css/sb-admin-2.min.css" rel="stylesheet">

</head>

<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <div class="sidebar-brand-icon rotate-n-15">
                <i class="fas fa-laugh-wink"></i>
            </div>
            <div class="sidebar-brand-text mx-3">Labor</div>
            </a>

            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Heading -->
            <div class="sidebar-heading">
                Welcome
            </div>


            <!-- Nav Item - Utilities Collapse Menu -->
            <li class="nav-item active">
                <a class="nav-link" href="#" data-toggle="collapse" data-target="#collapseUtilities"
                   aria-expanded="true" aria-controls="collapseUtilities">
                    <i class="fas fa-fw fa-wrench"></i>
                    <span>Groups</span>
                </a>
                <div id="collapseUtilities" class="collapse show" aria-labelledby="headingUtilities"
                     data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <a class="collapse-item active" href="/Account/Home">View your groups</a>
                        <a class="collapse-item" href="/Groups/AddGroup">Create a group</a>
                    </div>
                </div>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="/Account/ViewInvitation">
                    <i class="fas fa-fw fa-table"></i>
                    <span>Your invitation</span>
                </a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider d-none d-md-block">

            <!-- Sidebar Toggler (Sidebar) -->
            <div class="text-center d-none d-md-inline">
                <button class="rounded-circle border-0" id="sidebarToggle"></button>
            </div>

        </ul>
        <!-- End of Sidebar -->
        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                    <!-- Sidebar Toggle (Topbar) -->
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>

                    <!-- Topbar Navbar -->
                    <ul class="navbar-nav ml-auto">

                        <div class="topbar-divider d-none d-sm-block"></div>

                        <!-- Nav Item - User Information -->
                        <li class="nav-item dropdown no-arrow">
                            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span class="mr-2 d-none d-lg-inline text-gray-600 small">@User.FindFirst(ClaimTypes.Name)?.Value</span>
                            </a>
                            <!-- Dropdown - User Information -->
                            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                                 aria-labelledby="userDropdown">
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="~/Account/Logout">
                                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Logout
                                </a>
                            </div>
                        </li>

                    </ul>

                </nav>
                <!-- End of Topbar -->
                <!-- Begin Page Content -->
                <div class="container-fluid">

                    <!-- Page Heading -->
                    <h1 class="h3 mb-4 text-gray-800">Groups</h1>

                    <div class="row">

                        <div class="col-lg-12">

                            <!-- Circle Buttons -->
                            <div class="card shadow mb-4">
                                <div class="card-header py-3">
                                    <h6 class="m-0 font-weight-bold text-primary">View Member</h6>
                                    @if (null != usermember && usermember.RoleId == 1)
                                    {
                                        <a class="btn btn-info" style="text-decoration: none" asp-page="/Groups/InviteMember" asp-route-groupid="@gr.GroupId">Invite member</a>
                                    }
                                </div>
                                <div class="card-body">

                                    <table id="table_id" class="table table-bordered text-center" style="width:100%;">
                                        <thead class="text-uppercase bg-gray-200">
                                            <tr>
                                                <th style="width:60%;">Member name</th>
                                                <th style="width:20%;">Role</th>
                                                <th style="width:20%;"></th>
                                                <th style="width:20%;"></th>

                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach (var m in members)
                                            {
                                                <tr>
                                                    <td>@m.User.Fullname</td>
                                                    <td>@m.Role.RoleName</td>
                                                    @if (m.RoleId != 1 && usermember.RoleId == 1)
                                                    {

                                                        <td><a class="btn btn-success" style="text-decoration: none" asp-area="" asp-page="/Groups/UpdateMember" asp-route-userid="@m.UserId" asp-route-groupid="@m.GroupId">Update</a></td>
                                                        <td>
                                                            <form method="post" asp-route-userid="@m.UserId" asp-route-groupid="@m.GroupId" asp-page-handler="RemoveMember">
                                                                <button class="btn btn-danger" type="submit" onclick="return confirm('Are you sure?');">Remove</button>
                                                            </form>
                                                        </td>
                                                    }
                                                </tr>
                                            }
                                        </tbody>
                                    </table>
                                </div>
                            </div>


                        </div>

                    </div>

                </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->
            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; Your Website 2020</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->
    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Bootstrap core JavaScript-->
    <script src="~/js/jquery-3.4.1.min.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    <script src="~/js/jquery.min.js"></script>
    <script src="~/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/jquery.easing.min.js"></script>
    <!-- Custom scripts for all pages-->
    <script src="~/js/sb-admin-2.min.js"></script>

</body>

</html>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.11.3/css/jquery.dataTables.css">

<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.11.3/js/jquery.dataTables.js"></script>
<script>
    $(document).ready(function () {
        $('#table_id').DataTable();
    });
</script>