AssignmentPRN221_TaskManagement/Pages/Projects/AddProject.cshtml.cs
using AssignmentPRN221_TaskManagement.DataAccess;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Security.Claims;

namespace AssignmentPRN221_TaskManagement.Pages.Projects
{
    [Authorize]
    public class AddProjectModel : PageModel
    {
        GroupManagementContext context = new GroupManagementContext();
        public void OnGet(string groupid)
        {
            var identity = HttpContext.User.Identity as ClaimsIdentity;
            IEnumerable<Claim> claims = identity.Claims;
            string username = claims.FirstOrDefault(c => c.Type == ClaimTypes.Name)?.Value;
            User user = context.Users.SingleOrDefault(u => u.Username == username);
            Group group = context.Groups.SingleOrDefault(g => g.GroupId == int.Parse(groupid));

            ViewData["group"] = group;
            ViewData["user"] = user;
        }

        public void OnPost(string projectname, string description, string groupid)
        {
            var identity = HttpContext.User.Identity as ClaimsIdentity;
            IEnumerable<Claim> claims = identity.Claims;
            string username = claims.FirstOrDefault(c => c.Type == ClaimTypes.Name)?.Value;
            User user = context.Users.SingleOrDefault(u => u.Username == username);
            Group group = context.Groups.SingleOrDefault(g => g.GroupId == int.Parse(groupid));
            ViewData["user"] = user;
            ViewData["group"] = group;

            Project project = new Project();
            project.ProjectName = projectname;
            project.Description = description;
            project.Createdate = DateTime.Now;
            project.Group = group;
            project.Status = true;
            context.Projects.Add(project);
            context.SaveChanges();

            ViewData["MessAddProject"] = "Add Project successfully";
        }
    }
}

AssignmentPRN221_TaskManagement/Pages/Projects/ViewProject.cshtml.cs
using AssignmentPRN221_TaskManagement.DataAccess;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;

namespace AssignmentPRN221_TaskManagement.Pages.Projects
{
    [Authorize]
    public class ViewProjectModel : PageModel
    {
        GroupManagementContext context = new GroupManagementContext();
        public IActionResult OnGet(string groupid)
        {
            var identity = HttpContext.User.Identity as ClaimsIdentity;
            IEnumerable<Claim> claims = identity.Claims;
            string username = claims.FirstOrDefault(c => c.Type == ClaimTypes.Name)?.Value;

            User user = context.Users.SingleOrDefault(u => u.Username == username && u.Status == true);
            Member member = context.Members.FirstOrDefault(m => m.UserId == user.UserId && m.Group.GroupId == int.Parse(groupid) && m.Status == true);

            if (member == null)
            {
                return RedirectToPage("/AccessDenied");
            }

            List<Project> projects = context.Projects.Include(p => p.Group.Members).Where(p => p.Group.Members.Contains(member) && p.GroupId == int.Parse(groupid) && p.Status == true).ToList();
            Group group = context.Groups.SingleOrDefault(g => g.GroupId == int.Parse(groupid));

            ViewData["group"] = group;
            ViewData["user"] = user;
            ViewData["projects"] = projects;

            return Page();
        }

        public IActionResult OnPostRemoveProject(string projectid, string groupid)
        {
            Project project = context.Projects.SingleOrDefault(p => p.ProjectId == int.Parse(projectid));
            project.Status = false;
            context.SaveChanges();


            ViewData["MessProjectRemove"] = "Remove Project successfully";


            var identity = HttpContext.User.Identity as ClaimsIdentity;
            IEnumerable<Claim> claims = identity.Claims;
            string username = claims.FirstOrDefault(c => c.Type == ClaimTypes.Name)?.Value;

            User user = context.Users.SingleOrDefault(u => u.Username == username && u.Status == true);
            Member member = context.Members.FirstOrDefault(m => m.UserId == user.UserId && m.Group.GroupId == int.Parse(groupid) && m.Status == true);

            if (member == null)
            {
                return RedirectToPage("/AccessDenied");
            }
            List<Project> projects = context.Projects.Include(p => p.Group.Members).Where(p => p.Group.Members.Contains(member) && p.GroupId == int.Parse(groupid) && p.Status == true).ToList();
            Group group = context.Groups.SingleOrDefault(g => g.GroupId == int.Parse(groupid));

            ViewData["group"] = group;
            ViewData["user"] = user;
            ViewData["projects"] = projects;

            return Page();
        }
    }
}

AssignmentPRN221_TaskManagement/Pages/Projects/AddProject.cshtml
@page
@using AssignmentPRN221_TaskManagement.DataAccess
@using System.Security.Claims;
@model AssignmentPRN221_TaskManagement.Pages.Projects.AddProjectModel
@{
    Layout = null;
    User user = (User)ViewData["user"];
    Group gr = (Group)ViewData["group"];
    var MessAddProject = ViewData["MessAddProject"];
}


<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>HomePage</title>

    <!-- Custom fonts for this template-->
    <script src="https://kit.fontawesome.com/aca8a481b2.js" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
          rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="~/css/sb-admin-2.min.css" rel="stylesheet">

</head>

<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <div class="sidebar-brand-icon rotate-n-15">
                <i class="fas fa-laugh-wink"></i>
            </div>
            <div class="sidebar-brand-text mx-3">Labor</div>
            </a>

            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Heading -->
            <div class="sidebar-heading">
                Welcome
            </div>


            <!-- Nav Item - Utilities Collapse Menu -->
            <li class="nav-item active">
                <a class="nav-link" href="#" data-toggle="collapse" data-target="#collapseUtilities"
                   aria-expanded="true" aria-controls="collapseUtilities">
                    <i class="fas fa-fw fa-wrench"></i>
                    <span>Projects</span>
                </a>
                <div id="collapseUtilities" class="collapse show" aria-labelledby="headingUtilities"
                     data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <a class="collapse-item" asp-page="/Projects/ViewProject" asp-route-groupid="@gr.GroupId">View Projects</a>
                        <a class="collapse-item active" asp-page="/Projects/AddProject" asp-route-groupid="@gr.GroupId">Add Project</a>
                    </div>
                </div>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="/Account/ViewInvitation">
                    <i class="fas fa-fw fa-table"></i>
                    <span>Your invitation</span>
                </a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider d-none d-md-block">

            <!-- Sidebar Toggler (Sidebar) -->
            <div class="text-center d-none d-md-inline">
                <button class="rounded-circle border-0" id="sidebarToggle"></button>
            </div>

        </ul>
        <!-- End of Sidebar -->
        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                    <!-- Sidebar Toggle (Topbar) -->
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>

                    <!-- Topbar Navbar -->
                    <ul class="navbar-nav ml-auto">

                        <div class="topbar-divider d-none d-sm-block"></div>

                        <!-- Nav Item - User Information -->
                        <li class="nav-item dropdown no-arrow">
                            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span class="mr-2 d-none d-lg-inline text-gray-600 small">@User.FindFirst(ClaimTypes.Name)?.Value</span>
                            </a>
                            <!-- Dropdown - User Information -->
                            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                                 aria-labelledby="userDropdown">
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="~/Account/Logout">
                                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Logout
                                </a>
                            </div>
                        </li>

                    </ul>

                </nav>
                <!-- End of Topbar -->



                <div class="container-fluid">
                    <h1 class="h3 mb-4 text-gray-800">Projects</h1>
                    <div class="row">

                        <div class="col-lg-12">

                            <!-- Circle Buttons -->
                            <div class="card shadow mb-4">
                                <div class="card-header py-3">
                                    <h6 class="m-0 font-weight-bold text-primary">Add Project</h6>
                                </div>
                                <h6 class="text-danger">@MessAddProject</h6>
                                    <form method="post" class="form-addgroup">
                                    <table class="table">
                                        <tr>
                                            <td style="width: 30%;"><strong>Project Name</strong></td>
                                            <td style="width: 70%;">
                                                <input pattern="[^' ']+" class="form-control" type="text" name="projectname" required>
                                                <div class="invalid-feedback">
                                                    Not blank and no space at beginning or ending
                                                </div>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td><strong>Description</strong></td>
                                            <td>
                                                <textarea pattern="[^' ']+" class="form-control" type="text" name="description" required></textarea>
                                                <div class="invalid-feedback">
                                                    Not blank and no space
                                                </div>
                                            </td>
                                        </tr>

                                        <tr>
                                            <td></td>
                                            <td>
                                                <input type="hidden" value="@gr.GroupId" name="groupid" />
                                                <input type="submit" value="Add Project" class="btn btn-primary">
                                                <input type="reset" value="Reset" class="btn btn-info" />
                                            </td>
                                        </tr>

                                    </table>
                                    </form>
                            </div>


                        </div>

                    </div>


                </div>


                <!-- Bootstrap core JavaScript-->
                <script src="~/js/jquery-3.4.1.min.js"></script>
                <script src="~/js/bootstrap.min.js"></script>
                <script src="~/js/jquery.min.js"></script>
                <script src="~/js/bootstrap.bundle.min.js"></script>
                <script src="~/js/jquery.easing.min.js"></script>
                <!-- Custom scripts for all pages-->
                <script src="~/js/sb-admin-2.min.js"></script>

</body>

</html>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.11.3/css/jquery.dataTables.css">

<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.11.3/js/jquery.dataTables.js"></script>
<script>
    $(document).ready(function () {
        $('#table_id').DataTable();
    });
</script>

AssignmentPRN221_TaskManagement/Pages/Projects/ViewProject.cshtml
@page
@model AssignmentPRN221_TaskManagement.Pages.Projects.ViewProjectModel
@using AssignmentPRN221_TaskManagement.DataAccess
@using System.Security.Claims;
@{
    Layout = null;
    User user = (User)ViewData["user"];
    List<Project> projects = (List<Project>)ViewData["projects"];
    Group gr = (Group)ViewData["group"];
    var MessProjectRemove = ViewData["MessProjectRemove"];
}

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>HomePage</title>

    <!-- Custom fonts for this template-->
    <script src="https://kit.fontawesome.com/aca8a481b2.js" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
          rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="~/css/sb-admin-2.min.css" rel="stylesheet">

</head>

<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <div class="sidebar-brand-icon rotate-n-15">
                <i class="fas fa-laugh-wink"></i>
            </div>
            <div class="sidebar-brand-text mx-3">Labor</div>
            </a>

            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Heading -->
            <div class="sidebar-heading">
                Welcome
            </div>


            <!-- Nav Item - Utilities Collapse Menu -->
            <li class="nav-item active">
                <a class="nav-link" href="#" data-toggle="collapse" data-target="#collapseUtilities"
                   aria-expanded="true" aria-controls="collapseUtilities">
                    <i class="fas fa-fw fa-wrench"></i>
                    <span>Projects</span>
                </a>
                <div id="collapseUtilities" class="collapse show" aria-labelledby="headingUtilities"
                     data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <a class="collapse-item active" asp-page="/Projects/ViewProject" asp-route-groupid="@gr.GroupId">View Projects</a>
                        <a class="collapse-item" asp-page="/Projects/AddProject" asp-route-groupid="@gr.GroupId">Add Project</a>
                    </div>
                </div>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="/Account/ViewInvitation">
                    <i class="fas fa-fw fa-table"></i>
                    <span>Your invitation</span>
                </a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider d-none d-md-block">

            <!-- Sidebar Toggler (Sidebar) -->
            <div class="text-center d-none d-md-inline">
                <button class="rounded-circle border-0" id="sidebarToggle"></button>
            </div>

        </ul>
        <!-- End of Sidebar -->
        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                    <!-- Sidebar Toggle (Topbar) -->
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>

                    <!-- Topbar Navbar -->
                    <ul class="navbar-nav ml-auto">

                        <div class="topbar-divider d-none d-sm-block"></div>

                        <!-- Nav Item - User Information -->
                        <li class="nav-item dropdown no-arrow">
                            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span class="mr-2 d-none d-lg-inline text-gray-600 small">@User.FindFirst(ClaimTypes.Name)?.Value</span>
                            </a>
                            <!-- Dropdown - User Information -->
                            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                                 aria-labelledby="userDropdown">
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="~/Account/Logout">
                                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Logout
                                </a>
                            </div>
                        </li>

                    </ul>

                </nav>
                <!-- End of Topbar -->
                <!-- Begin Page Content -->
                <div class="container-fluid">

                    <!-- Page Heading -->
                    <h1 class="h3 mb-4 text-gray-800">Projects</h1>

                    <div class="row">

                        <div class="col-lg-12">

                            <!-- Circle Buttons -->
                            <div class="card shadow mb-4">
                                <div class="card-header py-3">
                                </div>
                                <div class="card-body">
                                    <h6 class="m-0 font-weight-bold text-danger">@MessProjectRemove</h6>
                                    <table id="table_id" class="table table-bordered text-center" style="width:100%;">
                                        <thead class="text-uppercase bg-gray-200">
                                            <tr>
                                                <th style="width:10%;">Project name</th>
                                                <th style="width:20%;">Description</th>
                                                <th style="width:20%;">Create Date</th>
                                                @if (user.UserId == 1)
                                                {
                                                    <th style="width:10%;">Action</th>
                                                }
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach (var p in projects)
                                            {
                                                <tr>
                                                    <td> <a style="text-decoration: none" asp-area="" asp-page="/Issues/ViewIssue" asp-route-projectid="@p.ProjectId" asp-route-groupid="@gr.GroupId">@p.ProjectName </a></td>
                                                    <td>@p.Description</td>
                                                    <td>
                                                        @{
                                                            string date = p.Createdate.Value.ToString("dd-MM-yyyy");
                                                        }
                                                        @date
                                                    </td>
                                                    @if (user.UserId == 1)
                                                    {
                                                        <form method="post" asp-route-projectid="@p.ProjectId" asp-route-groupid="@gr.GroupId" asp-page-handler="RemoveProject">
                                                        <td><button class="btn btn-danger" type="submit">Remove</button></td>
                                                        </form>
                                                    }
                                                </tr>
                                            }
                                        </tbody>
                                    </table>
                                </div>
                            </div>


                        </div>

                    </div>

                </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->
            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; Your Website 2020</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->
    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Bootstrap core JavaScript-->
    <script src="~/js/jquery-3.4.1.min.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    <script src="~/js/jquery.min.js"></script>
    <script src="~/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/jquery.easing.min.js"></script>
    <!-- Custom scripts for all pages-->
    <script src="~/js/sb-admin-2.min.js"></script>

</body>

</html>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.11.3/css/jquery.dataTables.css">

<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.11.3/js/jquery.dataTables.js"></script>
<script>
    $(document).ready(function () {
        $('#table_id').DataTable();
    });
</script>