AssignmentPRN221_TaskManagement/Pages/Issues/AddIssue.cshtml.cs
using AssignmentPRN221_TaskManagement.DataAccess;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics.Metrics;
using System.Security.Claims;
using System.Text.RegularExpressions;
using Group = AssignmentPRN221_TaskManagement.DataAccess.Group;

namespace AssignmentPRN221_TaskManagement.Pages.Issues
{
    [Authorize]
    public class AddIssueModel : PageModel
    {
        GroupManagementContext context = new GroupManagementContext();
        public void OnGet(string projectid, string groupid)
        {
            var identity = HttpContext.User.Identity as ClaimsIdentity;
            IEnumerable<Claim> claims = identity.Claims;
            string username = claims.FirstOrDefault(c => c.Type == ClaimTypes.Name)?.Value;
            User user = context.Users.SingleOrDefault(u => u.Username == username && u.Status == true);
            Group group = context.Groups.SingleOrDefault(g => g.GroupId == int.Parse(groupid));
            Project project = context.Projects.SingleOrDefault(p => p.ProjectId == int.Parse(projectid));
            List<Member> members = context.Members.Include(m => m.User).Where(m => m.GroupId == int.Parse(groupid) && m.State == 1 && m.Status == true).ToList();

            ViewData["user"] = user;
            ViewData["members"] = members;
            ViewData["group"] = group;
            ViewData["project"] = project;
        }

        public void OnPost(string projectid, string groupid, string title, DateTime duedate, DateTime startdate, string description, string content, string assignee)
        {
            var identity = HttpContext.User.Identity as ClaimsIdentity;
            IEnumerable<Claim> claims = identity.Claims;
            string username = claims.FirstOrDefault(c => c.Type == ClaimTypes.Name)?.Value;
            User user = context.Users.SingleOrDefault(u => u.Username == username && u.Status == true);
            Group group = context.Groups.SingleOrDefault(g => g.GroupId == int.Parse(groupid));
            Project project = context.Projects.SingleOrDefault(p => p.ProjectId == int.Parse(projectid));
            List<Member> members = context.Members.Include(m => m.User).Where(m => m.GroupId == int.Parse(groupid) && m.State == 1 && m.Status == true).ToList();

            ViewData["user"] = user;
            ViewData["members"] = members;
            ViewData["group"] = group;
            ViewData["project"] = project;

            Issue issue = new Issue { Assignee = int.Parse(assignee), Content = content, Creator = user.UserId, Description = description, DueDate = duedate, ProjectId = int.Parse(projectid), StartDate = startdate, Title = title, State = 1, Status = true };
            context.Issues.Add(issue);
            context.SaveChanges();
            ViewData["MessAddIssue"] = "Add issue success!";
        }
    }
}

AssignmentPRN221_TaskManagement/Pages/Issues/EditIssue.cshtml.cs
using AssignmentPRN221_TaskManagement.DataAccess;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Security.Claims;

namespace AssignmentPRN221_TaskManagement.Pages.Issues
{
    [Authorize]
    public class EditIssueModel : PageModel
    {
        GroupManagementContext context = new GroupManagementContext();
        public void OnGet(string issueid, string groupid, string projectid)
        {
            var identity = HttpContext.User.Identity as ClaimsIdentity;
            IEnumerable<Claim> claims = identity.Claims;
            string username = claims.FirstOrDefault(c => c.Type == ClaimTypes.Name)?.Value;
            User user = context.Users.SingleOrDefault(u => u.Username == username && u.Status == true);
            Issue issue = context.Issues.SingleOrDefault(i => i.IssueId == int.Parse(issueid) && i.Status == true);
            Group group = context.Groups.SingleOrDefault(g => g.GroupId == int.Parse(groupid));
            Project project = context.Projects.SingleOrDefault(p => p.ProjectId == int.Parse(projectid));


            ViewData["user"] = user;
            ViewData["issue"] = issue;
            ViewData["group"] = group;
            ViewData["project"] = project;
        }

        public void OnPost(string issueid, string groupid, string projectid, string title, DateTime duedate, DateTime startdate, string description, string content, string state)
        {
            var identity = HttpContext.User.Identity as ClaimsIdentity;
            IEnumerable<Claim> claims = identity.Claims;
            string username = claims.FirstOrDefault(c => c.Type == ClaimTypes.Name)?.Value;
            User user = context.Users.SingleOrDefault(u => u.Username == username && u.Status == true);
            Issue issue = context.Issues.SingleOrDefault(i => i.IssueId == int.Parse(issueid) && i.Status == true);
            Group group = context.Groups.SingleOrDefault(g => g.GroupId == int.Parse(groupid));
            Project project = context.Projects.SingleOrDefault(p => p.ProjectId == int.Parse(projectid));


            ViewData["user"] = user;
            ViewData["issue"] = issue;
            ViewData["group"] = group;
            ViewData["project"] = project;

            if (title != null)
            {
                issue.Title = title;
            }
            if (description != null)
            {
                issue.Description = description;
            }
            if (content != null)
            {
                issue.Content = content;
            }
            issue.DueDate = duedate;
            issue.StartDate = startdate;
            issue.State = int.Parse(state);
            context.SaveChanges();
            ViewData["MessEditIssue"] = "Update succesfully!";

        }
    }
}

AssignmentPRN221_TaskManagement/Pages/Issues/ViewIssue.cshtml.cs
using AssignmentPRN221_TaskManagement.DataAccess;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;
using System.Text.RegularExpressions;
using Group = AssignmentPRN221_TaskManagement.DataAccess.Group;

namespace AssignmentPRN221_TaskManagement.Pages.Issues
{
    [Authorize]
    public class ViewIssueModel : PageModel
    {
        GroupManagementContext context = new GroupManagementContext();
        public IActionResult OnGet(string projectid, string groupid)
        {
            var identity = HttpContext.User.Identity as ClaimsIdentity;
            IEnumerable<Claim> claims = identity.Claims;
            string username = claims.FirstOrDefault(c => c.Type == ClaimTypes.Name)?.Value;
            User user = context.Users.SingleOrDefault(u => u.Username == username && u.Status == true);
            Member member = context.Members.SingleOrDefault(m => m.GroupId == int.Parse(groupid) && m.UserId == user.UserId && m.Status == true);
            Group group = context.Groups.SingleOrDefault(g => g.GroupId == int.Parse(groupid));
            Project project = context.Projects.SingleOrDefault(p => p.ProjectId == int.Parse(projectid));

            if (member == null || project == null || project.GroupId != group.GroupId)
            {
                return RedirectToPage("/AccessDenied");
            }

            List<Issue> issues = context.Issues.Include(i => i.Project).Where(i => i.ProjectId == int.Parse(projectid) && i.Status == true).ToList();

            ViewData["user"] = user;
            ViewData["member"] = member;
            ViewData["group"] = group;
            ViewData["project"] = project;
            ViewData["issues"] = issues;
            return Page();
        }

        public IActionResult OnPostRemoveIssue(string projectid, string groupid, string issueid)
        {
            var identity = HttpContext.User.Identity as ClaimsIdentity;
            IEnumerable<Claim> claims = identity.Claims;
            string username = claims.FirstOrDefault(c => c.Type == ClaimTypes.Name)?.Value;
            User user = context.Users.SingleOrDefault(u => u.Username == username && u.Status == true);
            Member member = context.Members.SingleOrDefault(m => m.GroupId == int.Parse(groupid) && m.UserId == user.UserId && m.Status == true);
            Group group = context.Groups.SingleOrDefault(g => g.GroupId == int.Parse(groupid));
            Project project = context.Projects.SingleOrDefault(p => p.ProjectId == int.Parse(projectid));
            Issue issue = context.Issues.SingleOrDefault(i => i.IssueId == int.Parse(issueid) && i.Status == true);
            issue.Status = false;
            context.SaveChanges();


            if (member == null || project == null || project.GroupId != group.GroupId)
            {
                return RedirectToPage("/AccessDenied");
            }

            List<Issue> issues = context.Issues.Include(i => i.Project).Where(i => i.ProjectId == int.Parse(projectid) && i.Status == true).ToList();

            ViewData["user"] = user;
            ViewData["member"] = member;
            ViewData["group"] = group;
            ViewData["project"] = project;
            ViewData["issues"] = issues;

            return Page();
        }
    }
}

AssignmentPRN221_TaskManagement/Pages/Issues/ViewIssue.cshtml
@page
@using AssignmentPRN221_TaskManagement.DataAccess
@using System.Security.Claims;
@model AssignmentPRN221_TaskManagement.Pages.Issues.ViewIssueModel
@{
    Layout = null;
    User user = (User)ViewData["user"];

    List<Issue> issues = (List<Issue>)ViewData["issues"];

    Member member = (Member)ViewData["member"];
    Project project = (Project)ViewData["project"];
    Group gr = (Group)ViewData["group"];
    var MessRemoveIssue = ViewData["MessRemoveIssue"];


    GroupManagementContext context = new GroupManagementContext();
}


<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>HomePage</title>

    <!-- Custom fonts for this template-->
    <script src="https://kit.fontawesome.com/aca8a481b2.js" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
          rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="~/css/sb-admin-2.min.css" rel="stylesheet">

</head>

<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <div class="sidebar-brand-icon rotate-n-15">
                <i class="fas fa-laugh-wink"></i>
            </div>
            <div class="sidebar-brand-text mx-3">Labor</div>
            </a>

            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Heading -->
            <div class="sidebar-heading">
                Welcome
            </div>


            <!-- Nav Item - Utilities Collapse Menu -->
            <li class="nav-item active">
                <a class="nav-link" href="#" data-toggle="collapse" data-target="#collapseUtilities"
                   aria-expanded="true" aria-controls="collapseUtilities">
                    <i class="fas fa-fw fa-wrench"></i>
                    <span>Issues</span>
                </a>
                <div id="collapseUtilities" class="collapse show" aria-labelledby="headingUtilities"
                     data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <a class="collapse-item active" asp-page="/Issues/ViewIssue" asp-route-projectid="@project.ProjectId" asp-route-groupid="@gr.GroupId">View Issues</a>
                        <a class="collapse-item" asp-page="/Issues/AddIssue" asp-route-projectid="@project.ProjectId" asp-route-groupid="@gr.GroupId">Add Issue</a>
                    </div>
                </div>
            </li>



            <li class="nav-item">
                <a class="nav-link" href="/Account/ViewInvitation">
                    <i class="fas fa-fw fa-table"></i>
                    <span>Your invitation</span>
                </a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider d-none d-md-block">

            <!-- Sidebar Toggler (Sidebar) -->
            <div class="text-center d-none d-md-inline">
                <button class="rounded-circle border-0" id="sidebarToggle"></button>
            </div>

        </ul>
        <!-- End of Sidebar -->
        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                    <!-- Sidebar Toggle (Topbar) -->
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>

                    <!-- Topbar Navbar -->
                    <ul class="navbar-nav ml-auto">

                        <div class="topbar-divider d-none d-sm-block"></div>

                        <!-- Nav Item - User Information -->
                        <li class="nav-item dropdown no-arrow">
                            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span class="mr-2 d-none d-lg-inline text-gray-600 small">@User.FindFirst(ClaimTypes.Name)?.Value</span>
                            </a>
                            <!-- Dropdown - User Information -->
                            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                                 aria-labelledby="userDropdown">
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="~/Account/Logout">
                                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Logout
                                </a>
                            </div>
                        </li>

                    </ul>

                </nav>
                <!-- End of Topbar -->
                <!-- Begin Page Content -->
                <div class="container-fluid">

                    <!-- Page Heading -->
                    <h1 class="h3 mb-4 text-gray-800">Projects</h1>

                    <div class="row">

                        <div class="col-lg-12">

                            <!-- Circle Buttons -->
                            <div class="card shadow mb-4">
                                <div class="card-header py-3">
                                    <h6 class="m-0 font-weight-bold text-primary">Issues</h6>
                                </div>
                                <div class="card-body">
                                    <!-- Circle Buttons (Default) -->
                                    <div class="table-responsive">
                                        <table id="table_id" style="width: 100%;" class="table text-center">
                                            <thead class="text-uppercase bg-gray-200">
                                                <tr>
                                                    <th style="width: 15%">Issue Name</th>
                                                    <th style="width: 20%">Start Date</th>
                                                    <th style="width: 20%">Due Date</th>
                                                    <th style="width: 10%">Create</th>
                                                    <th style="width: 10%">Assignee</th>
                                                    <th style="width: 10%">State</th>
                                                    @if (member.RoleId == 1)
                                                    {
                                                            <th style="width: 15%">Action</th>
                                                    }
                                                </tr>
                                            </thead>
                                            <tbody>
                                                @foreach (var item in issues)
                                                {


                                                        <tr>
                                                        @{

                                                            User creator = context.Users.Find(item.Creator);
                                                            User assignee = context.Users.Find(item.Assignee);
                                                        }
                                                            <td>
                                                            @if (member.UserId == item.Assignee || member.UserId == item.Creator)
                                                            {
                                                                        <a style="text-decoration: none;" asp-area="" asp-page="/Issues/EditIssue" asp-route-issueid="@item.IssueId" asp-route-projectid="@project.ProjectId" asp-route-groupid="@gr.GroupId">@item.Title</a>
                                                            }
                                                            else
                                                            {
                                                                @item.Title
                                                            }

                                                            </td>
                                                        @{
                                                            string startdate = item.StartDate.Value.ToString("dd-MM-yyyy");
                                                        }
                                                        @{
                                                            string duedate = item.DueDate.Value.ToString("dd-MM-yyyy");
                                                        }
                                                            <td>@startdate</td>
                                                            <td>@duedate</td>

                                                            <td>@creator.Fullname</td>
                                                            <td>@assignee.Fullname</td>
                                                        @if (item.State == 0)
                                                        {
                                                                    <td style="back: purple">Postpone</td>
                                                        }
                                                        else if (item.State == 1)
                                                        {
                                                                    <td style="color: blue">Doing</td>
                                                        }
                                                        else
                                                        {
                                                                    <td style="color: green">Done</td>
                                                        }


                                                        @if (member.RoleId == 1 && item.Status == true)
                                                        {
                                                                    <td>
                                                                        <form method="post" asp-route-projectid="@project.ProjectId" asp-route-groupid="@gr.GroupId" asp-route-issueid="@item.IssueId" asp-page-handler="RemoveIssue">
                                                                    <button class="btn btn-danger" type="submit" onclick="return confirm('Are you sure?');">Remove</button>
                                                                    </form>
                                                                    </td>


                                                        }

                                                        </tr>
                                                }
                                            </tbody>
                                        </table>
                                    </div>

                                </div>
                            </div>


                        </div>

                    </div>

                </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->
            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; Your Website 2020</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->
    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Bootstrap core JavaScript-->
    <script src="~/js/jquery-3.4.1.min.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    <script src="~/js/jquery.min.js"></script>
    <script src="~/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/jquery.easing.min.js"></script>
    <!-- Custom scripts for all pages-->
    <script src="~/js/sb-admin-2.min.js"></script>

</body>

</html>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.11.3/css/jquery.dataTables.css">

<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.11.3/js/jquery.dataTables.js"></script>
<script>
    $(document).ready(function () {
        $('#table_id').DataTable();
        "fnDrawCallback": function(oSettings) {
            if ($('#example tr').length < 11) {
                $('.dataTables_paginate').hide();
            }
        }
    });
</script>